---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Tools:
    - ChatGPT:
        icon: chatgpt.png
        href: "https://chat.openai.com/"
        description: ChatGPT

- APIs:
    - ollama:
        icon: ollama.png
        href: "http://localhost:11434/"
        description: Ollama API
        widgets:
          - type: customapi
            url: http://host.docker.internal:11434/api/tags
            method: GET
            display: dynamic-list
            mappings:
              items: models
              name: details.family
              label: model
          - type: customapi
            url: http://host.docker.internal:11434/api/ps
            method: GET
            mappings:
              - field: models
                label: loaded models
                format: size
              - field: models.0.size_vram
                label: VRAM used
                format: bytes
